"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.isVersionedTransaction = exports.WalletNotConnectedError = exports.WalletSendTransactionError = exports.WalletSignMessageError = exports.WalletSignTransactionError = exports.WalletPublicKeyError = exports.WalletAccountError = exports.WalletDisconnectionError = exports.WalletDisconnectedError = exports.WalletConnectionError = exports.WalletConfigError = exports.WalletLoadError = exports.WalletNotReadyError = exports.WalletError = exports.BaseMessageSignerWalletAdapter = exports.scopePollingDetectionStrategy = exports.isIosAndRedirectable = exports.WalletReadyState = exports.BaseWalletAdapter = exports.EventEmitter = void 0;
const eventemitter3_1 = __importDefault(require("eventemitter3"));
exports.EventEmitter = eventemitter3_1.default;
var adapter_1 = require("./adapter");
Object.defineProperty(exports, "BaseWalletAdapter", { enumerable: true, get: function () { return adapter_1.BaseWalletAdapter; } });
Object.defineProperty(exports, "WalletReadyState", { enumerable: true, get: function () { return adapter_1.WalletReadyState; } });
Object.defineProperty(exports, "isIosAndRedirectable", { enumerable: true, get: function () { return adapter_1.isIosAndRedirectable; } });
Object.defineProperty(exports, "scopePollingDetectionStrategy", { enumerable: true, get: function () { return adapter_1.scopePollingDetectionStrategy; } });
var signer_1 = require("./signer");
Object.defineProperty(exports, "BaseMessageSignerWalletAdapter", { enumerable: true, get: function () { return signer_1.BaseMessageSignerWalletAdapter; } });
var errors_1 = require("./errors");
Object.defineProperty(exports, "WalletError", { enumerable: true, get: function () { return errors_1.WalletError; } });
Object.defineProperty(exports, "WalletNotReadyError", { enumerable: true, get: function () { return errors_1.WalletNotReadyError; } });
Object.defineProperty(exports, "WalletLoadError", { enumerable: true, get: function () { return errors_1.WalletLoadError; } });
Object.defineProperty(exports, "WalletConfigError", { enumerable: true, get: function () { return errors_1.WalletConfigError; } });
Object.defineProperty(exports, "WalletConnectionError", { enumerable: true, get: function () { return errors_1.WalletConnectionError; } });
Object.defineProperty(exports, "WalletDisconnectedError", { enumerable: true, get: function () { return errors_1.WalletDisconnectedError; } });
Object.defineProperty(exports, "WalletDisconnectionError", { enumerable: true, get: function () { return errors_1.WalletDisconnectionError; } });
Object.defineProperty(exports, "WalletAccountError", { enumerable: true, get: function () { return errors_1.WalletAccountError; } });
Object.defineProperty(exports, "WalletPublicKeyError", { enumerable: true, get: function () { return errors_1.WalletPublicKeyError; } });
Object.defineProperty(exports, "WalletSignTransactionError", { enumerable: true, get: function () { return errors_1.WalletSignTransactionError; } });
Object.defineProperty(exports, "WalletSignMessageError", { enumerable: true, get: function () { return errors_1.WalletSignMessageError; } });
Object.defineProperty(exports, "WalletSendTransactionError", { enumerable: true, get: function () { return errors_1.WalletSendTransactionError; } });
Object.defineProperty(exports, "WalletNotConnectedError", { enumerable: true, get: function () { return errors_1.WalletNotConnectedError; } });
var transaction_1 = require("./transaction");
Object.defineProperty(exports, "isVersionedTransaction", { enumerable: true, get: function () { return transaction_1.isVersionedTransaction; } });
//# sourceMappingURL=index.js.map